version: "3.1"
services:

  nginix-proxy:
    image: jwilder/nginx-proxy
    container_name: nginix-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frontend

  db93:
    image: postgres:9.3
    container_name: postgres-9.3
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./_db93:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks: 
      - backend
  
  db94:
    image: postgres:9.4
    container_name: postgres-9.4
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./_db94:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks: 
      - backend
  
  db95:
    image: postgres:9.5
    container_name: postgres-9.5
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./_db95:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks: 
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge